tap "caskroom/cask"
tap "drone/drone"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "isen-ng/dotnet-sdk-versions"
tap "jakehilborn/jakehilborn"

# Package Managers & Sys tools
brew "dockutil"
brew "mackup"
brew "mas"
cask "displayplacer"
cask "mysides"

# Fun & Social
cask "battle-net"
cask "discord"
cask "pulse-sms"
cask "signal"
cask "slack"
cask "spotify-notifications"
cask "spotify"
cask "steam"
cask "vlc"
cask "vox"

# Productivity & General
brew "p7zip"
cask "1password"
cask "brave-browser"
cask "dropbox"
cask "flux"
cask "google-backup-and-sync"
cask "microsoft-office"
cask "nordvpn"
cask "notion"
cask "numi"
cask "quicken"
cask "rescuetime"
cask "selfcontrol"
mas "1440", id: 1483764819
mas "Day One", id: 1055511498
mas "Horo", id: 1437226581
mas "Monosnap", id: 540348655
mas "Pocket", id: 568494494
mas "Todoist", id: 585829637
mas "Yoink", id: 457622435

# Power User
cask "alfred"
cask "balenaetcher"
cask "bartender"
cask "cakebrew"
cask "cheatsheet"
cask "disk-inventory-x"
cask "imageoptim"
cask "little-snitch"
cask "macs-fan-control"
cask "micro-snitch"
cask "monolingual"
cask "onyx"
cask "soundflower"
cask "tor-browser"
cask "tunnelblick"
cask "uhk-agent"
cask "vmware-fusion"
cask "wkhtmltopdf" # Renders html to pdf
mas "Disk Speed Test", id: 425264550

# Quicklook plugins
cask "apparency"
cask "jupyter-notebook-ql"
cask "provisionql"
cask "qladdict"
cask "qlcolorcode"
cask "qlcommonmark"
cask "qlfits"
cask "qlgradle"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlmobi"
cask "qlplayground"
cask "qlprettypatch"
cask "qlstephen"
cask "qlswift"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklook-pat"
cask "quicklookapk"
cask "suspicious-package"
cask "webpquicklook"

# Dev
brew "ack"
brew "autojump"
brew "awscli"
brew "findutils"
brew "fzf"
brew "gmp"
brew "gnu-sed --with-default-names"
brew "gnupg"
brew "grep"
brew "lftp"
brew "moreutils"
brew "nvm"
brew "openjdk"
brew "openssh"
brew "php"
brew "rsync"
brew "scrcpy"
brew "ssh-copy-id", link: true
brew "telnet"
brew "tldr"
brew "tree"
brew "vim --with-override-system-vi"
brew "wget --with-iri"
cask "dash"
cask "font-firacode-nerd-font"
cask "insomnia"
cask "iterm2"
cask "java"
cask "visual-studio-code"
cask "wireshark"
mas "OhMyStar", id: 1218642292
mas "Xcode", id: 497799835

brew "libpq"
brew "postgresql"
cask "postico"

brew "go"
brew "golang-migrate"
brew "swagger-codegen"
brew "terraform"
brew "wakatime-cli"
cask "goland"

brew "git-credential-manager"
brew "git-extras"
brew "git-lfs"
brew "git"
brew "zsh-git-prompt"
cask "beyond-compare"
cask "diff-so-fancy"
cask "gitkraken"

brew "zsh-history-substring-search"
brew "zsh-lovers"
brew "zsh-navigation-tools"
brew "zsh"

brew "apm-bash-completion"
brew "cargo-completion"
brew "django-completion"
brew "gem-completion"
brew "gradle-completion"
brew "grunt-completion"

brew "docker-completion"
brew "docker-compose-completion"
brew "docker-compose", link: false
brew "docker-machine-completion"
cask "docker"
